paths:
  dataset_path: data/Beauty_TIGER_varlen_cond_entropy_bpe_top128_f20_s10_usage10
  output_dir: experiment/Beauty_TIGER_varlen_cond_entropy_bpe_top128_f20_s10_usage10_seq2seq
  split_data_paths:
    train: data/Beauty_TIGER_varlen_cond_entropy_bpe_top128_f20_s10_usage10/train_seq2seq_letter_fixed_target.json
    val: data/Beauty_TIGER_varlen_cond_entropy_bpe_top128_f20_s10_usage10/val_seq2seq_letter_fixed_target.json
    test: data/Beauty_TIGER_varlen_cond_entropy_bpe_top128_f20_s10_usage10/test_seq2seq_letter_fixed_target.json

tokenizer:
  codeword_nums:
    - 256
    - 256
    - 256
    - 256
  extra_semantic_tokens_path: data/Beauty_TIGER_varlen_cond_entropy_bpe_top128_f20_s10_usage10/varlen_meta.json

model:
  model_type: t5-rec
  model_arch: seq2seq
  max_seq_length: 512
  hidden_size: 128
  intermediate_size: 1024
  num_hidden_layers: 4
  num_decoder_layers: 4
  num_attention_heads: 6
  rms_norm_eps: 1.0e-06
  dropout_rate: 0.1
  feed_forward_proj: relu
  tie_word_embeddings: true
  semantic_embedding_init: none
  semantic_embedding_projection: random
  pattern_embedding_init: none
  pattern_embedding_init_path: data/Beauty_TIGER_varlen_cond_entropy_bpe_top128_f20_s10_usage10/varlen_meta.json
  pattern_embedding_freeze: false
  semantic_embedding_freeze_scope: none

runtime:
  preprocess_num_proc: 1

training:
  per_device_train_batch_size: 256
  per_device_eval_batch_size: 32
  gradient_accumulation_steps: 2
  learning_rate: 0.0005
  num_train_epochs: 200
  lr_scheduler_type: cosine
  warmup_ratio: 0.01
  weight_decay: 0.01
  early_stopping_patience: 20
  fp16: true
  report_to: tensorboard
  remove_unused_columns: false
  batch_eval_metrics: true
  logging_steps: 100
  save_strategy: epoch
  save_total_limit: 2
  eval_strategy: epoch
  metric_for_best_model: eval_loss
  greater_is_better: false
  load_best_model_at_end: true

evaluation:
  validation_objective: loss
  eval_split: val
  eval_k_values:
    - 1
    - 5
    - 10
  num_beams: 20
  evaluation_mode: both
  generation_constraint: full_trie
  sid_to_pid_mapping_path: data/Beauty_TIGER/Beauty.sid2pid.json
  pid_selection_strategy: sample_by_count
  pid_random_seed: 42
